### ISSUE TITLE
Build fails at 45% :react-native-android-kit:compileReleaseJavaWithJavac

### ISSUE THREAD

**Issue by zjjt** [ayoubdev/react-native-android-kit#17]
I am trying to buil an apk to test on my phone and it fails.Can you help me figure this out?
here's my log:

cd android && ./gradlew :app:installDebug --stacktrace
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-android-kit:compileLint
:react-native-android-kit:copyReleaseLint UP-TO-DATE
:react-native-android-kit:preBuild UP-TO-DATE
:react-native-android-kit:preReleaseBuild UP-TO-DATE
:react-native-android-kit:checkReleaseManifest
:react-native-android-kit:preDebugAndroidTestBuild UP-TO-DATE
:react-native-android-kit:preDebugBuild UP-TO-DATE
:react-native-android-kit:preDebugUnitTestBuild UP-TO-DATE
:react-native-android-kit:preReleaseUnitTestBuild UP-TO-DATE
:react-native-android-kit:prepareComAndroidSupportAnimatedVectorDrawable2340Library                                                                            UP-TO-DATE
:react-native-android-kit:prepareComAndroidSupportAppcompatV72340Library UP-TO-DATE
:react-native-android-kit:prepareComAndroidSupportDesign2340Library UP-TO-DATE
:react-native-android-kit:prepareComAndroidSupportRecyclerviewV72340Library UP-TO-DATE
:react-native-android-kit:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:react-native-android-kit:prepareComAndroidSupportSupportVectorDrawable2340Library                                                                             UP-TO-DATE
:react-native-android-kit:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:react-native-android-kit:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:react-native-android-kit:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:react-native-android-kit:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:react-native-android-kit:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:react-native-android-kit:prepareComFacebookFrescoImagepipelineOkhttp30110Library                                                                              UP-TO-DATE
:react-native-android-kit:prepareComFacebookReactReactNative0320Library UP-TO-DATE
:react-native-android-kit:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:react-native-android-kit:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-android-kit:prepareReleaseDependencies
:react-native-android-kit:compileReleaseAidl UP-TO-DATE
:react-native-android-kit:compileReleaseRenderscript UP-TO-DATE
:react-native-android-kit:generateReleaseBuildConfig UP-TO-DATE
:react-native-android-kit:generateReleaseAssets UP-TO-DATE
:react-native-android-kit:mergeReleaseAssets UP-TO-DATE
:react-native-android-kit:generateReleaseResValues UP-TO-DATE
:react-native-android-kit:generateReleaseResources UP-TO-DATE
:react-native-android-kit:mergeReleaseResources UP-TO-DATE
:react-native-android-kit:processReleaseManifest UP-TO-DATE
:react-native-android-kit:processReleaseResources UP-TO-DATE
:react-native-android-kit:generateReleaseSources UP-TO-DATE
:react-native-android-kit:processReleaseJavaRes UP-TO-DATE
:react-native-android-kit:compileReleaseJavaWithJavac
/Users/zehijeanjacquesthibaut/Desktop/TRIZ_DIGITAL/WEBAPPS_MOBILE_APPS/NSIA/NsiaVieMob/NsiaVieMobileApp/node_modules/react-native-android-kit/android/src/main/java/fr/ayoubdev/rnak/components/button/ButtonNode.java:10: error: ButtonNode is not abstract and does not override abstract method measure(CSSNodeAPI,float,CSSMeasureMode,float,CSSMeasureMode,MeasureOutput) in MeasureFunction
public class ButtonNode extends LayoutShadowNode implements CSSNode.MeasureFunction {
       ^
/Users/zehijeanjacquesthibaut/Desktop/TRIZ_DIGITAL/WEBAPPS_MOBILE_APPS/NSIA/NsiaVieMob/NsiaVieMobileApp/node_modules/react-native-android-kit/android/src/main/java/fr/ayoubdev/rnak/components/button/ButtonNode.java:19: error: method does not override or implement a method from a supertype
	@Override
	^
/Users/zehijeanjacquesthibaut/Desktop/TRIZ_DIGITAL/WEBAPPS_MOBILE_APPS/NSIA/NsiaVieMob/NsiaVieMobileApp/node_modules/react-native-android-kit/android/src/main/java/fr/ayoubdev/rnak/components/floatingbutton/FabNode.java:10: error: FabNode is not abstract and does not override abstract method measure(CSSNodeAPI,float,CSSMeasureMode,float,CSSMeasureMode,MeasureOutput) in MeasureFunction
public class FabNode extends LayoutShadowNode implements CSSNode.MeasureFunction {
       ^
/Users/zehijeanjacquesthibaut/Desktop/TRIZ_DIGITAL/WEBAPPS_MOBILE_APPS/NSIA/NsiaVieMob/NsiaVieMobileApp/node_modules/react-native-android-kit/android/src/main/java/fr/ayoubdev/rnak/components/floatingbutton/FabNode.java:19: error: method does not override or implement a method from a supertype
	@Override
	^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors
:react-native-android-kit:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-android-kit:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-android-kit:compileReleaseJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:47)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:137)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:91)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:243)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:230)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 49 more

BUILD FAILED

Total time: 39.625 secs

**Comment by frontmesh** [comment]
I am getting the same error ```error: cannot find symbol
import com.facebook.csslayout.CSSMeasureMode;```

What version of react-native are you using in local @ayoubdev , I am guessing some pre release version ?

**Comment by ayoubdev** [comment]
Fixed on v1.1.3 release (cf. 23ab5f77b176882674db4682b00b4a3df2636d3f commit)

**Comment by zjjt** [comment]
thanks i will try it out
